services:
  db:
    image: postgres:17.7-trixie
    container_name: vindex-db
    environment:
      POSTGRES_USER: vindex
      POSTGRES_PASSWORD: vindex
      POSTGRES_DB: vindex
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: